# Use an official Node.js runtime as a parent image
FROM node:18-alpine as build-env

# Set the working directory to /app
WORKDIR /app

# Copy package.json and package-lock.json to /app
COPY package*.json ./

# Install app dependencies
RUN npm install

# Copy app source code to /app
COPY . .

# Build the app for production
RUN npm run build:prod

FROM nginx:alpine

COPY --from=build-env /app/dist/new-store /usr/share/nginx/html
COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 8080