export const translater: Record<string, string> = {
  accesories: 'Accesorios',
  active: '¿Activo?',
  assignmentStatus: 'Estado',
  assignmentTypeCodeName: 'Tipo de asignación',
  brandCodeName: 'Marca',
  callingPlanCodeName: 'Plan de llamadas',
  code: 'Código',
  description: 'Descripción',
  imei: 'IMEI',
  instanceLineAccountPhone: 'Línea de registro',
  lineContractName: 'Línea de contrato',
  name: 'Nombre',
  observations: 'Observaciones',
  phoneImei: 'IMEI',
  phoneModelCodeName: 'Modelo de teléfono',
  phoneSerialNumber: 'Número de serie',
  serialNumber: 'Número de serie',
  startDate: 'Fecha de inicio',
  toReplace: '¿A reemplazar?',
  callAmount: 'Monto de llamada',
  dataPlanAmount: 'Monto plan de datos',
  endDate: 'Fecha finalización',
  megabytePlan: 'Plan megabyte',
  winRate: 'Taza de éxito '
};
